/* autogenerated by Processing revision 1286 on 2025-12-17 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Prison_Escape extends PApplet {

// Torr Hardin, Janame Lindberg | Prison Escape

Player p1;
Map m1;
Key k1;
Door door;
ArrayList<Security> guards;

PImage bg1, go1;

boolean wPressed, aPressed, sPressed, dPressed, play;

 public void setup() {
  /* size commented out by preprocessor */;
  noCursor();


  m1 = new Map();
  p1 = new Player(300, -1700);
  k1 = new Key(600, 300, 80, 50);

  door = new Door(0, 1970, 100, 80);

  guards = new ArrayList<Security>();
  guards.add(new Security(-1700, -1000));
  guards.add(new Security(-1500, 300));
  guards.add(new Security(800, 1000));
  guards.add(new Security(000, 1700));
  guards.add(new Security(-1000, 1000));

  bg1 = loadImage("Prison Escape Start Screen.png");
  go1 = loadImage("Prison End Screen.png");

  play = false;
}

 public void draw() {
  if (!play) {
    startScreen();
    return;
  }

  background(179, 160, 89);

  // Camera
  pushMatrix();
  translate(width/2 - p1.x, height/2 - p1.y);

  m1.display();
  k1.display();
  door.display();

  // Display Guards
  for (Security g : guards) {
    g.display();
  }

  p1.display();
  popMatrix();

  // Movement
  float speed = 30;
  if (wPressed) p1.move(0, -speed);
  if (sPressed) p1.move(0,  speed);
  if (aPressed) p1.move(-speed, 0);
  if (dPressed) p1.move( speed, 0);

  // Check key pickup
  k1.checkPickup(p1);

  // Check door interaction
  door.checkPlayer(p1, k1);

  // Check guard collisions
  gameOver();
}

 public void keyPressed() {
  if (key == 'w' || key == 'W') wPressed = true;
  if (key == 's' || key == 'S') sPressed = true;
  if (key == 'a' || key == 'A') aPressed = true;
  if (key == 'd' || key == 'D') dPressed = true;

  if (!play && key == ' ') play = true;
}

 public void keyReleased() {
  if (key == 'w' || key == 'W') wPressed = false;
  if (key == 's' || key == 'S') sPressed = false;
  if (key == 'a' || key == 'A') aPressed = false;
  if (key == 'd' || key == 'D') dPressed = false;
}

 public void startScreen() {
  image(bg1, 0, 0, width, height);
}

// Collision
 public boolean collideRect(float x1, float y1, float w1, float h1,
                    float x2, float y2, float w2, float h2) {
  return !(x1 + w1 < x2 ||
           x1 > x2 + w2 ||
           y1 + h1 < y2 ||
           y1 > y2 + h2);
}

// Check Player Guard Collision
 public void gameOver() {

  float px = p1.x - p1.r;
  float py = p1.y - p1.r;
  float pw = p1.w;
  float ph = p1.h;

  for (Security g : guards) {
    float gx = g.x - g.r;
    float gy = g.y - g.r;
    float gw = g.r * 2;
    float gh = g.r * 2;

    if (collideRect(px, py, pw, ph, gx, gy, gw, gh)) {
      image(go1, 0, 0, width, height);
      noLoop();
      return;
    }
  }
}
// Janame Lindberg | Door Class

class Door {
  float x, y, w, h;
  PImage w2;
  boolean opened;

  Door(float x, float y, float w, float h) {
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
    opened = false;
    w2 = loadImage("Prison Escape Win Screen.png");
  }

   public void display() {
    fill(92, 68, 16);
    rect(this.x, this.y, this.w, this.h);
  }

   public void checkPlayer(Player p, Key k) {
    // Check Collision if Key Collected
    if (this.opened == false && k.collected == true) {
      float px = p.x - p.r;
      float py = p.y - p.r;
      float pw = p.w;
      float ph = p.h;

      boolean collidedX = px + pw >= this.x && px <= this.x + this.w;
      boolean collidedY = py + ph >= this.y && py <= this.y + this.h;

      if (collidedX && collidedY) {
        this.opened = true;
        image(this.w2, 0, 0, width, height);
        noLoop();
      }
    }
  }
}
// Torr Hardin | Key Class

class Key {
  float x, y;
  float w, h;
  PImage img;
  boolean collected = false;  // has the player picked it up?

  Key(float x, float y, float w, float h) {
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
    img = loadImage("Prison Escape Key.png");
  }

   public void display() {
    if (!collected) {
      image(img, x, y, w, h);
    }
  }

  // Check for Collision with Player
   public void checkPickup(Player p) {
    if (!collected) {
      float px = p.x - p.r;
      float py = p.y - p.r;
      float pw = p.w;
      float ph = p.h;

      if (!(px + pw < x || px > x + w || py + ph < y || py > y + h)) {
        collected = true;
      }
    }
  }
}
// Janame Lindberg | Map Class

class Map {

  int floorColor = color(100); 

  ArrayList<Wall> walls;

  Map() {
    walls = new ArrayList<Wall>();

    // Exterior Walls
    walls.add(new Wall(-2000, -2000, 4000, 50));
    walls.add(new Wall(-2000, -2000, 50, 4000));
    walls.add(new Wall(-2000, 2000, 4050, 50));
    walls.add(new Wall(2000, -2000, 50, 4000));

    // Bottom of Prisoner Zone
    walls.add(new Wall(-1700, -600, 2200, 50));

    // Cell 1
    walls.add(new Wall(-1500, -2000, 50, 750));
    walls.add(new Wall(-2000, -1300, 350, 50));
    
    // Cell 2
    walls.add(new Wall(-1000, -2000, 50, 750));
    walls.add(new Wall(-1500, -1300, 350, 50));
    
    // Cell 3
    walls.add(new Wall(-500, -2000, 50, 750));
    walls.add(new Wall(-1000, -1300, 350, 50));
    
    // Cell 4
    walls.add(new Wall(0, -2000, 50, 750));
    walls.add(new Wall(-500, -1300, 350, 50));
    
    // Cell 5
    walls.add(new Wall(500, -2000, 50, 1000));
    walls.add(new Wall(0, -1300, 350, 50));
    
    // Cafeteria and Kitchen
    walls.add(new Wall(500, -800, 50, 1400));
    walls.add(new Wall(500, 0, 1300, 50));
    walls.add(new Wall(500, 600, 1500, 50));
    
    // Gym
    walls.add(new Wall(-1700, 600, 2200, 50));
    walls.add(new Wall(-1600, -600, 50, 1000));
    
    // Guard Area
    walls.add(new Wall(500, 600, 50, 1200));
    
  }

   public void display() {

    // Floor
    fill(floorColor);
    rect(-2000, -2000, 4000, 4000);

    // Walls
    fill(50);
    for (Wall w : walls) {
      w.display();
    }
  }
}
// Torr Hardin | Player Class

class Player {
  float x, y;
  float r = 40;
  float w, h;
  PImage p2;

  Player(float x, float y) {
    this.p2 = loadImage("prisoner 1.png");
    this.x = x;
    this.y = y;
    this.w = r * 2;
    this.h = r * 3.2f;
  }

   public void display() {
    image(this.p2, this.x - r, this.y - r, this.w, this.h);
  }

   public void move(float dx, float dy) {
    float newX = this.x + dx;
    float newY = this.y + dy;

    if (!collidesWithWalls(newX, this.y)) {
      this.x = newX;
    }

    if (!collidesWithWalls(this.x, newY)) {
      this.y = newY;
    }
  }

   public boolean collidesWithWalls(float checkX, float checkY) {
    float px = checkX - r; // left of sprite
    float py = checkY - r; // top of sprite
    float pw = this.w;
    float ph = this.h;

    for (Wall w : m1.walls) {
      if (collideRect(px, py, pw, ph, w.x, w.y, w.w, w.h)) {
        return true;
      }
    }
    return false;
  }
}
// Torr Hardin | Security Class

class Security {
  float x, y;
  float r = 40;
  float w, h;
  PImage s2;

  Security(float x, float y) {
    s2 = loadImage("guard 1.png");
    this.x = x;
    this.y = y;

    w = r * 2;
    h = r * 3.2f;
  }

   public void display() {
    image(s2, x - r, y - r, w, h);
  }
}
// Janame Lindberg | Wall Class

class Wall {
  float x, y, w, h;

  Wall(float x, float y, float w, float h) {
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
  }

   public void display() {
    rect(x, y, w, h);
  }
}


  public void settings() { fullScreen(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Prison_Escape" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
